python main.py \
    --name 'Glow_CIFAR10_K16_L3' \
    --load \
    --ckpt Glow_MNIST_K16_L3/epoch_1 \
    --start_from_step 600 \
    --save_period 200 \
    --epochs 100 \
    --learning_rate 1e-3 \
    --dequantized \
    --nn_kernel 3 \
    --nn_channels 512 \
    --channels 3 \
    --width 32 \
    --height 32 \
    --K 16 \
    --L 3