python main.py \
    --name 'Glow_CIFAR10_K16_L3' \
    --save_period 200 \
    --epochs 100 \
    --learning_rate 1e-3 \
    --dequantized \
    --nn_kernel 3 \
    --nn_channels 512 \
    --channels 3 \
    --width 32 \
    --height 32 \
    --K 32 \
    --L 3